import test from 'node:test';
import assert from 'node:assert/strict';
import {createProject,createView,geometry,constrain,outputSize,validateProject,presetFromView,applyPreset} from '../src/engine.js';
import {isDefaultImage,syncPortraitProject} from '../src/actor-images.js';
import {buildActorPatch,buildScenePatch,applyTransaction} from '../foundry/transaction.js';
test('retratos e tokens têm estados independentes e preservam a origem',()=>{const p=createProject('original.png');p.views.token.x=.4;p.views.token.zoom=2;assert.equal(p.views.portrait.x,0);assert.equal(p.views.portrait.zoom,1);assert.equal(p.views.token.src,'original.png');assert.notEqual(p.views.token,p.views.portrait);});
test('Preencher cobre todos os cantos sem deformar, mesmo com rotação e imagens extremas',()=>{
  for(const dims of [{width:50,height:2000},{width:2000,height:50},{width:1024,height:1024},{width:4000,height:3000}])for(const rotation of [-175,-90,-45,0,33,90,177])for(const aspect of ['1:1','2:3','16:9']){
    const v={...createView('x.png'),rotation,aspect,x:5,y:-5,zoom:1.7},size=outputSize(v);const c=constrain(v,dims,size.width,size.height),g=geometry(c,dims,size.width,size.height);
    for(const x of [-g.cropW/2,g.cropW/2])for(const y of [-g.cropH/2,g.cropH/2]){const dx=x-c.x*size.width,dy=y-c.y*size.height,lx=(g.c*dx+g.s*dy)/g.scale,ly=(-g.s*dx+g.c*dy)/g.scale;assert.ok(Math.abs(lx)<=dims.width/2+1e-7);assert.ok(Math.abs(ly)<=dims.height/2+1e-7);}
  }
});
test('Mostrar inteira inclui os quatro cantos da imagem no recorte circular',()=>{for(const dims of [{width:200,height:900},{width:900,height:200},{width:512,height:512}])for(const rotation of [0,25,90]){const v={...createView('x'),fit:'contain',rotation},g=geometry(v,dims,512,512);for(const x of [-dims.width/2,dims.width/2])for(const y of [-dims.height/2,dims.height/2])assert.ok(Math.hypot((g.c*x-g.s*y)*g.scale/(g.cropW/2),(g.s*x+g.c*y)*g.scale/(g.cropH/2))<=1+1e-9);}});
test('Livre mantém deslocamentos; Preencher impede zoom insuficiente',()=>{const image={width:1200,height:400};const free=constrain({...createView('x'),fit:'free',x:3,y:-4,zoom:.2},image);assert.equal(free.x,3);assert.equal(free.y,-4);assert.equal(free.zoom,.2);assert.equal(constrain({...free,fit:'cover'},image).zoom,1);});
test('presets transferem estilo sem substituir a imagem original',()=>{const a={...createView('a.png'),color:'#abcdef',zoom:2},b=createView('b.png');assert.equal(applyPreset(b,presetFromView(a)).src,'b.png');assert.equal(applyPreset(b,presetFromView(a)).color,'#abcdef');});
test('importação rejeita projetos corrompidos e fontes executáveis',()=>{const p=createProject('x.png');assert.equal(validateProject(p),p);for(const mutate of [p=>p.schema=9,p=>p.views.token.zoom=NaN,p=>p.views.token.aspect='0:0',p=>p.views.token.src='javascript:alert(1)',p=>p.views.token.frameSrc='data:image/svg+xml;base64,AAAA']){const invalid=structuredClone(p);mutate(invalid);assert.throws(()=>validateProject(invalid));}});
test('aplicar somente retrato não modifica token, estatísticas ou escala',()=>{const p=createProject('x'),patch=buildActorPatch(p,{portrait:true,prototype:false},{portrait:'new.png'});assert.equal(patch.img,'new.png');assert.ok(!Object.keys(patch).some(k=>k.startsWith('prototypeToken')));assert.ok(!Object.keys(patch).some(k=>k.startsWith('system')));});
test('moldura própria desliga anel duplicado; anel nativo recebe a nova arte',()=>{const p=createProject('x'),t={id:'one',ring:{enabled:true}};assert.equal(buildScenePatch([t],p,{token:'new.png'})[0]['ring.enabled'],false);p.views.token.frame='none';assert.equal(buildScenePatch([t],p,{token:'new.png'})[0]['ring.subject.texture'],'new.png');assert.equal(buildActorPatch(p,{prototype:true},{token:'new.png'},{prototypeToken:{ring:{enabled:true}}})['prototypeToken.ring.subject.texture'],'new.png');});
function fixture(){const actorCalls=[],sceneCalls=[];return{actor:{img:'old-portrait',prototypeToken:{texture:{src:'old-token'},ring:{enabled:true,subject:{texture:'old-subject'}}},getFlag:()=>({old:true}),update:async p=>{actorCalls.push(p);}},scene:{updateEmbeddedDocuments:async(type,p)=>{sceneCalls.push(p);}},tokens:[{id:'t1',texture:{src:'old-scene'},ring:{enabled:true,subject:{texture:'old-scene-subject'}}}],actorCalls,sceneCalls,project:createProject('x'),paths:{portrait:'new-portrait',token:'new-token'},destinations:{portrait:true,prototype:true,scene:true}};}
test('aplicação atualiza apenas os tokens informados e usa uma única atualização do ator',async()=>{const f=fixture();await applyTransaction(f);assert.equal(f.actorCalls.length,1);assert.equal(f.sceneCalls[0].length,1);assert.equal(f.sceneCalls[0][0]._id,'t1');assert.equal(f.actorCalls[0].img,'new-portrait');});
test('falha na cena restaura ficha, token padrão e tokens da cena',async()=>{const f=fixture();let call=0;f.scene.updateEmbeddedDocuments=async(type,p)=>{f.sceneCalls.push(p);if(!call++)throw new Error('fail');};await assert.rejects(applyTransaction(f),/anteriores foram restauradas/);assert.equal(f.actorCalls[1].img,'old-portrait');assert.equal(f.actorCalls[1]['prototypeToken.texture.src'],'old-token');assert.equal(f.sceneCalls[1][0]['texture.src'],'old-scene');assert.equal(f.sceneCalls[1][0]['ring.subject.texture'],'old-scene-subject');});
test('falha na atualização do ator não inicia atualização de cena',async()=>{const f=fixture();f.actor.update=async()=>{throw new Error('permission');};await assert.rejects(applyTransaction(f),/permission/);assert.equal(f.sceneCalls.length,0);});
test('falha na restauração não é apresentada como sucesso',async()=>{const f=fixture();f.scene.updateEmbeddedDocuments=async()=>{throw new Error('offline');};await assert.rejects(applyTransaction(f),/Confira a ficha/);});

test('novo retrato preserva o token personalizado e só substitui arte padrão',()=>{
 const project=createProject('old.png');Object.assign(project.views.token,{src:'custom.webp',zoom:2.7,x:.4,rotation:35,frame:'gold'});const before=structuredClone(project);
 const next=syncPortraitProject(project,'compcon.webp');assert.equal(next.views.portrait.src,'compcon.webp');assert.deepEqual(next.views.token,before.views.token);assert.deepEqual(project,before);
 project.views.token.src='/vtt/modules/token-studio/assets/pilot.png';const seeded=syncPortraitProject(project,'compcon.webp');assert.equal(seeded.views.token.src,'compcon.webp');assert.equal(seeded.views.token.zoom,2.7);assert.equal(seeded.views.token.frame,'gold');
 assert.ok(isDefaultImage('/vtt/systems/lancer/assets/icons/white/pilot.svg'));assert.ok(!isDefaultImage('my-pilot.svg'));assert.ok(!isDefaultImage('systems/lancer/assets/my-custom.png'));
});
